### ISSUE TITLE
Could not get images for weather radar: Error fetching information. Keep the existing radar data.

### ISSUE THREAD

**Issue by AndyVRD** [jdejaegh/irm-kmi-ha#36]
**Describe the bug**
Keep getting this warning x times each hour.

**Version**
Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

IRM KMI 0.2.14

**Additional context**
Just installed the integration and getting the below error x times per hour.
`Could not get images for weather radar: Error fetching information. Keep the existing radar data.`

Can it be releated that i use the camera entity in a picture-entity card?

```
type: picture-entity
show_state: false
show_name: false
entity: camera.radar_home
camera_view: live
```

**Comment by jdejaegh** [comment]
This warning is logged when the integration could not get the data needed to show the radar animation from the API.  Generally, it is because the API times out or is unreachable. Except waiting and retrying later there nothing you can really do.

For you information, my instance logged the same error 11 times between 12:45PM and 2:20PM today.  The IRM API was probably down for some time during this period.

When only the radar images cannot be fetched (but forecast and everything else works), the radar just keeps the exiting data to show the animation.

Could you retry on your side and tell me if it works now?

**Comment by jdejaegh** [comment]
Good then!

The situation already improved: previously, any API error when fetching the data caused all the entities to show `unkown`. Now, only the failed parts are kept as they were and it retries at the next poll interval.

I'll close the issue as this comes from the API timing out. Feel free to reach out if you encounter some bugs
