### ISSUE TITLE
Shifted values and missing day

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [jdejaegh/irm-kmi-ha#8]
On the following screenshot, met.no data above and IRM below:

![Screenshot_20240121-004407](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/8874bf3a-71ae-4d8c-b82a-778d563be832)

Sunday temperature should go to 6°C instead of zero. And Thursday is missing.

While reporting this, Sunday got fixed but Wednesday vanished. This all happened between midnight and 1.00.
![Screenshot_20240121-004933~2](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/3bd4e5ea-70e7-4bdd-b88a-c0a37548eea9)

For reference:
![Screenshot_20240121-005711](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/129ab0e3-799c-43cc-9ef5-d2e7703acce9)
Have they inverted the tonight and Sunday values?

Also of interest: Wednesday's night value is higher the during the day. This might have wrecked havoc in your logic.

**Comment by jdejaegh** [comment]
Thanks for opening the issue.

I assume that you are using this custom card for your dashboard: https://github.com/pkissling/clock-weather-card

I see two issues here: the first one where Sunday temperature was -2°C, 0°C instead of -2°C, 6°C (your expected values); the second one where the days are not showing on the card.

**Incorrect Sunday temperature**
As I don't have any data to reproduce it I cannot really do much here.  Could you provide at least a screenshot of the IRM app with the same location? 

**Missing days on the card**
Using the screenshot you provided for this issue, I mocked the forecast value to return the conditions and temperatures shown in the IRM app.  When used on my dashboard, I conclude that the issue is coming from the custom card you use.  Below is a screenshot of two cards showing this weather data.  On top, your custom card; below, the stock Lovelace weather card.  The stock card shows all the days, including Wednesday; while the custom card does not. 

If the IRM API says that the temperature is higher during the night (13°C) and lower during the day (12°C), it seems weird for the integration to swap the values.  I suggest to open an issue on the custom card repository instead.

![Screenshot 2024-01-21 at 14-42-12 Overview – Home Assistant](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/6900ab32-3620-44e2-8597-a0deb7e6ec09)

**Comment by patriiiiiiiiiick** [comment]
> I assume that you are using this custom card for your dashboard: https://github.com/pkissling/clock-weather-card

Correct

> Could you provide at least a screenshot of the IRM app with the same location?

This is the last screenshot I put.

But yeah, it all seems linked and due to the custom card.

Thanks for your time!

**Comment by jdejaegh** [comment]
I went through the issue you opened on the custom card repository and the comment https://github.com/pkissling/clock-weather-card/issues/324#issuecomment-1902713407 has a good point.  Home Assistant documentation is not about night or day temperature but lower and higher.

I reopen this and will fix the attributes when I can.

This will avoid other edge cases and ensure that the integration follows Home Assistant documentation.  Thanks for reporting this!
